# Generated by Django 6.0.1 on 2026-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
