# Generated by Django 6.0.1 on 2026-05-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
